version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  execution:
    build: execution
    environment:
      - BUILDER_TX_SIGNING_KEY=${BUILDER_TX_SIGNING_KEY}
    volumes:
      - execution-data:/data
      - secrets:/secrets
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    command: [
      "--builder=true",
      "--builder.remote_relay_endpoint=https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money",
      "--builder.secondary_remote_relay_endpoints=https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net,https://0xa7ab7a996c8584251c8f925da3170bdfd6ebc75d50f5ddc4050a6fdc77f2a3b5fce2cc750d0865e05d7228af97d69561@agnostic-relay.net,https://0xa15b52576bcbf1072f4a011c0f99f9fb6c66f3e1ff321f11f461d15e31b1cb359caa092c71bbded0bae5b5ea401aab7e@aestus.live,https://0x98650451ba02064f7b000f5768cf0cf4d4e492317d82871bdc87ef841a0743f69f0f1eea11168503240ac35d101c9135@mainnet-relay.securerpc.com,https://0xb3ee7afcf27f1f1259ac1787876318c6584ee353097a50ed84f51a1f21a323b3736f271a895c7ce918c038e4265918be@relay.edennetwork.io,https://0x84e78cb2ad883861c9eeeb7d1b22a8e02332637448f84144e245d20dff1eb97d7abdde96d4e7f80934e5554e11915c56@relayooor.wtf",
      "--builder.beacon_endpoint=http://consensus:5052/",
      "--builder.bellatrix_fork_version=0x02000000",
      "--builder.genesis_fork_version=0x00000000",
      "--builder.genesis_validators_root=0x0000000000000000000000000000000000000000000000000000000000000000",
      "--builder.secret_key=${BUILDER_TX_SIGNING_KEY}",
      "--datadir=/data",
      "--syncmode=snap",
      "--port=30303",
      "--http",
      "--http.vhosts=*",
      "--http.corsdomain=*",
      "--http.addr=0.0.0.0",
      "--http.port=8545",
      "--http.api=admin,debug,web3,eth,txpool,personal,miner,net,builder,engine",
      "--ws",
      "--ws.api=web3,eth,txpool,net",
      "--ws.addr=0.0.0.0",
      "--ws.port=8546",
      "--pprof",
      "--pprof.addr=0.0.0.0",
      "--metrics",
      "--metrics.expensive",
      "--authrpc.addr=0.0.0.0",
      "--authrpc.port=8551",
      "--authrpc.jwtsecret=/secrets/jwtsecret",
      "--authrpc.vhosts=*",
      "--verbosity=3",
      "--miner.algotype=greedy",
      "--miner.extradata=${BUILDER_EXTRA_DATA}",
      "--miner.etherbase=${BUILDER_ADDRESS}",
    ]
    <<: *logging

  consensus:
    build: consensus
    volumes:
      - consensus-data:/data
      - secrets:/secrets
    ports:
      - "5052:5052"
      - "9000:9000"
      - "13000:13000"
    command: [
      "--accept-terms-of-use",
      "--execution-endpoint=http://execution:8551",
      "--jwt-secret=/secrets/jwtsecret",
      "--suggested-fee-recipient=${BUILDER_ADDRESS}",
      "--datadir=/data",
      "--checkpoint-sync-url=${BEACON_API_URL}",
      "--genesis-beacon-api-url=${BEACON_API_URL}",
      "--rpc-host=0.0.0.0",
      "--grpc-gateway-host=0.0.0.0",
      "--grpc-gateway-port=5052",
      "--monitoring-host=0.0.0.0",
      "--monitoring-port=8008",
      "--p2p-tcp-port=9000",
      "--p2p-udp-port=9000",
    ]
    <<: *logging

  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    volumes:
      - prom-data:/prometheus
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--storage.tsdb.path=/prometheus", 
      "--web.console.libraries=/usr/share/prometheus/console_libraries", 
      "--web.console.templates=/usr/share/prometheus/consoles"
    ]
    <<: *logging
    depends_on:
      - node-exporter
      - blackbox-exporter
      - json-exporter
      - cryptowat-exporter
      - cadvisor
      - ethereum-metrics-exporter

  ethereum-metrics-exporter:
    image: samcm/ethereum-metrics-exporter
    command: [
      "--consensus-url=http://consensus:5052",
      "--execution-url=http://execution:8545",
    ]
    restart: unless-stopped
    <<: *logging
    depends_on:
      - execution
      - consensus

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command: [
      "--path.rootfs=/host",
      "--path.procfs=/host/proc",
      "--path.sysfs=/host/sys",
      "--collector.filesystem.ignored-mount-points='^/(dev|proc|sys|run|var/lib/docker/.+)($$|/)'",
      "--no-collector.ipvs",
    ]
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
      - /etc/hostname:/etc/nodename:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    depends_on:
      - execution
      - consensus

  blackbox-exporter:
    restart: unless-stopped
    image: prom/blackbox-exporter:master
    volumes:
      - ./prometheus/blackbox.yml:/config/blackbox.yml
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    command:
      - --config.file=/config/blackbox.yml
    depends_on:
      - execution
      - consensus

  json-exporter:
    restart: unless-stopped
    image: quay.io/prometheuscommunity/json-exporter
    volumes:
      - ./prometheus/json.yml:/config/json.yml
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    command:
      - --config.file
      - /config/json.yml
    depends_on:
      - execution
      - consensus

  cryptowat-exporter:
    restart: unless-stopped
    image: nbarrientos/cryptowat_exporter
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CRYPTOWAT_EXCHANGES=kraken
      - CRYPTOWAT_PAIRS=ethusd,ethchf
      - CRYPTOWAT_CACHESECONDS=300
      - TZ=Europe/Zurich
    <<: *logging
    depends_on:
      - execution
      - consensus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    command:
      - --docker_only
      - --housekeeping_interval=30s
    <<: *logging
    depends_on:
      - execution
      - consensus

  promtail:
    image: grafana/promtail:latest
    user: root
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - ./promtail:/etc/promtail
      - promtail-data:/tmp
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command:
      - '--config.file=/etc/promtail/promtail.yml'
    restart: unless-stopped
    depends_on:
      - loki
      - execution
      - consensus
    <<: *logging

  loki:
    image: grafana/loki:latest
    volumes:
      - loki-data:/tmp
      - ./loki:/etc/loki
    command:
      - '--config.file=/etc/loki/loki.yml'
    restart: unless-stopped
    <<: *logging
    depends_on:
      - execution
      - consensus

  grafana:
    build:
      context: ./grafana
    image: grafana:local
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_HTTP_PORT=3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - prometheus
      - loki
      - promtail
      - execution
      - consensus
    entrypoint: ["provision-dashboards.sh"]
    command: /run.sh
    <<: *logging

volumes:
  execution-data:
  consensus-data:
  secrets:
  grafana-data:
  grafana-config:
  prom-data:
  loki-data:
  promtail-data:
